name=wEui
version=1.0.0
author=Wuqiyang312
maintainer=Wuqiyang312
sentence=Lightweight UI Library for Embedded Systems
paragraph=A simple and efficient UI library designed for embedded systems, featuring list management, button handling, and display rendering with U8g2 support.
category=Display
url=https://github.com/weui/weui
architectures=*
depends=U8g2
